name: Generate Snake

on:
  schedule: # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg
      - name: Commit & push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/
          git commit -m "Generate contribution snake" || exit 0
          git push
